/**
 * The `test_kinds` FIXTURE template: every item kind the engine admits, over a `month` period on the
 * `statements` anchor, so the leg 2 derivation is proven before the real close templates exist
 * (spec G22 §10.13). It is registered ONLY while `NODE_ENV=test` (`canon/index.ts` reads the variable
 * at call time) and never reaches a shipped template list, a generated document or a workspace.
 *
 * What it exercises, row by row: derived choices off the workspace row (`legal_form`), off the A07
 * method eras governing the period (`vat_method`), off A22's read
 * (`has_fc_positions`) and off the register (`has_assets`); a human choice with a pre-selected default
 * (`accruals_needed`, open until saved); a live check; a preview paired with a posting under an
 * inclusion and an `emptyWhen` pointer (`fx_preview` / `fx_posted`); a preview with no pointer paired
 * with the H04 probe (`depreciation_preview` / `depreciation_posted`); a preview whose verb is not
 * registered yet and a posting whose probe is an A38 stub (`accruals_preview` / `accruals_posted`:
 * `read_refused` and `needs_a38`); two `block` validations and two `warn` validations (one under a
 * legal-form inclusion, one that reads `unavailable` on a first year); the statements sign-off; the GV
 * attestation with the `gv_6_months` rule (null on a month); a `verb_result` bound through
 * `VERB_EVIDENCE`; and the month lock as a posting probed off A03 with a pacing offset.
 */

import type { ChecklistTemplate } from '../types.js';

export const TEST_KINDS_TEMPLATE_ID = 'test_kinds';

const YES_NO = [
  { id: 'yes', labelKey: 'checklists.choice.yes', consequenceKey: 'checklists.choice.yes.consequence' },
  { id: 'no', labelKey: 'checklists.choice.no', consequenceKey: 'checklists.choice.no.consequence' },
] as const;

export const TEST_KINDS_TEMPLATE: ChecklistTemplate = {
  templateId: TEST_KINDS_TEMPLATE_ID,
  kind: 'test_kinds',
  label: 'Testvorlage (alle Schritt-Arten)',
  description: 'Eine Vorlage nur für die Tests: jede Schritt-Art einmal, über einen Monat, am Abschluss-Anker.',
  periodKind: 'month',
  anchor: 'statements',
  items: [
    {
      itemId: 'legal_form',
      title: 'Rechtsform',
      ownerKind: 'system',
      evidenceKind: 'choice',
      derive: 'legal_form',
      options: [
        { id: 'einzelfirma', labelKey: 'checklists.choice.legalForm.einzelfirma', consequenceKey: 'checklists.choice.legalForm.einzelfirma.consequence' },
        { id: 'gmbh', labelKey: 'checklists.choice.legalForm.gmbh', consequenceKey: 'checklists.choice.legalForm.gmbh.consequence' },
        { id: 'ag', labelKey: 'checklists.choice.legalForm.ag', consequenceKey: 'checklists.choice.legalForm.ag.consequence' },
      ],
    },
    {
      itemId: 'vat_method',
      title: 'MWST-Methode',
      ownerKind: 'system',
      evidenceKind: 'choice',
      derive: 'vat_method',
      options: [
        { id: 'effektiv', labelKey: 'checklists.choice.vatMethod.effektiv', consequenceKey: 'checklists.choice.vatMethod.effektiv.consequence' },
        { id: 'saldo', labelKey: 'checklists.choice.vatMethod.saldo', consequenceKey: 'checklists.choice.vatMethod.saldo.consequence' },
        { id: 'none', labelKey: 'checklists.choice.vatMethod.none', consequenceKey: 'checklists.choice.vatMethod.none.consequence' },
      ],
    },
    {
      itemId: 'has_fc_positions',
      title: 'Fremdwährungspositionen vorhanden?',
      ownerKind: 'system',
      evidenceKind: 'choice',
      derive: 'has_fc_positions',
      options: YES_NO,
    },
    {
      itemId: 'has_assets',
      title: 'Anlagen vorhanden?',
      ownerKind: 'system',
      evidenceKind: 'choice',
      derive: 'has_assets',
      options: YES_NO,
    },
    {
      itemId: 'accruals_needed',
      title: 'Abgrenzungen für diesen Monat?',
      ownerKind: 'human',
      evidenceKind: 'choice',
      options: YES_NO,
      defaultOptionId: 'no',
      dueOffsetDays: 10,
    },
    {
      itemId: 'no_drafts',
      title: 'Keine Entwürfe bis Monatsende',
      ownerKind: 'system',
      evidenceKind: 'check',
      check: 'no_drafts',
      deepLink: '/journal',
      dueOffsetDays: 10,
    },
    {
      itemId: 'fx_preview',
      title: 'Fremdwährungsbewertung: Vorschau',
      ownerKind: 'human',
      evidenceKind: 'preview',
      verb: 'fx_revaluation',
      verbInput: 'periodEnd',
      emptyWhen: '/positions',
      deepLink: '/fx',
      prerequisiteItemId: 'has_fc_positions',
      includedWhen: { itemId: 'has_fc_positions', optionId: 'yes' },
      dueOffsetDays: 10,
    },
    {
      itemId: 'fx_posted',
      title: 'Fremdwährungsbewertung gebucht',
      ownerKind: 'human',
      evidenceKind: 'posting',
      verb: 'post_fx_revaluation',
      reverseVerb: 'fx_revaluation_reverse',
      verbInput: 'periodEnd',
      probe: 'fx_revaluation_posted',
      previewOf: 'fx_preview',
      deepLink: '/fx',
      includedWhen: { itemId: 'has_fc_positions', optionId: 'yes' },
      dueOffsetDays: 10,
    },
    {
      itemId: 'depreciation_preview',
      title: 'Abschreibungen: Vorschau',
      ownerKind: 'human',
      evidenceKind: 'preview',
      verb: 'asset_depreciation_preview',
      verbInput: 'lastMonth',
      deepLink: '/assets',
      prerequisiteItemId: 'has_assets',
      includedWhen: { itemId: 'has_assets', optionId: 'yes' },
      dueOffsetDays: 10,
    },
    {
      itemId: 'depreciation_posted',
      title: 'Abschreibungen gebucht',
      ownerKind: 'human',
      evidenceKind: 'posting',
      verb: 'asset_depreciation_run_post',
      reverseVerb: 'asset_depreciation_run_reverse',
      verbInput: 'lastMonth',
      probe: 'depreciation_charged',
      previewOf: 'depreciation_preview',
      deepLink: '/assets',
      includedWhen: { itemId: 'has_assets', optionId: 'yes' },
      dueOffsetDays: 10,
    },
    {
      itemId: 'accruals_preview',
      title: 'Abgrenzungen: Vorschau',
      ownerKind: 'human',
      evidenceKind: 'preview',
      verb: 'accrual_list',
      verbInput: 'periodEnd',
      deepLink: '/periods',
      prerequisiteItemId: 'accruals_needed',
      includedWhen: { itemId: 'accruals_needed', optionId: 'yes' },
      dueOffsetDays: 10,
    },
    {
      itemId: 'accruals_posted',
      title: 'Abgrenzungen gebucht',
      ownerKind: 'human',
      evidenceKind: 'posting',
      verb: 'accrual_post',
      reverseVerb: 'accrual_reverse',
      verbInput: 'periodEnd',
      probe: 'accruals_posted',
      previewOf: 'accruals_preview',
      deepLink: '/periods',
      includedWhen: { itemId: 'accruals_needed', optionId: 'yes' },
      dueOffsetDays: 10,
    },
    {
      itemId: 'balance_equation',
      title: 'Bilanz stimmt',
      ownerKind: 'system',
      evidenceKind: 'validation',
      validation: 'balance_equation',
      severity: 'block',
      fixLink: '/journal',
      dueOffsetDays: 10,
    },
    {
      itemId: 'open_items_reconciled',
      title: 'Offene Posten stimmen mit 1100',
      ownerKind: 'system',
      evidenceKind: 'validation',
      validation: 'open_items_debtors',
      severity: 'block',
      fixLink: '/journal?account=1100',
      dueOffsetDays: 10,
    },
    {
      itemId: 'capital_loss_check',
      title: 'Kein Kapitalverlust',
      ownerKind: 'system',
      evidenceKind: 'validation',
      validation: 'capital_loss',
      severity: 'warn',
      fixLink: '/reports',
      prerequisiteItemId: 'legal_form',
      includedWhen: { itemId: 'legal_form', optionId: 'gmbh' },
      deadlineRule: 'umsatzabstimmung_180',
    },
    {
      itemId: 'prior_year_check',
      title: 'Vorjahresvergleich',
      ownerKind: 'system',
      evidenceKind: 'validation',
      validation: 'prior_year_comparison',
      severity: 'warn',
      fixLink: '/reports',
      dueOffsetDays: 10,
    },
    {
      itemId: 'statements_signed',
      title: 'Bilanz und Erfolgsrechnung freigegeben',
      ownerKind: 'human',
      evidenceKind: 'signoff',
      signoffKind: 'statements_signoff',
      deepLink: '/reports',
      prerequisiteItemIds: ['balance_equation', 'open_items_reconciled'],
      undeletable: true,
      dueOffsetDays: 20,
    },
    {
      itemId: 'gv_approved',
      title: 'Generalversammlung hat die Jahresrechnung genehmigt',
      ownerKind: 'human',
      evidenceKind: 'signoff',
      signoffKind: 'gv_attestation',
      deepLink: '/reports',
      prerequisiteItemId: 'statements_signed',
      includedWhen: { itemId: 'legal_form', optionId: 'gmbh' },
      deadlineRule: 'gv_6_months',
    },
    {
      itemId: 'berichtigung_filed',
      title: 'Berichtigungsabrechnung eingereicht',
      ownerKind: 'human',
      evidenceKind: 'filed_attestation',
      signoffKind: 'filed_attestation',
      deepLink: '/mwst',
      prerequisiteItemId: 'statements_signed',
      deadlineRule: 'berichtigung_240',
    },
    {
      itemId: 'depreciation_previewed',
      title: 'Abschreibungen berechnet',
      ownerKind: 'agent',
      evidenceKind: 'verb_result',
      verb: 'asset_depreciation_preview',
      verbInput: 'lastMonth',
      deepLink: '/assets',
      dueOffsetDays: 10,
    },
    {
      itemId: 'lock_on_month',
      title: 'Monat abschliessen',
      ownerKind: 'human',
      evidenceKind: 'posting',
      verb: 'close_month',
      reverseVerb: 'reopen_month',
      verbInput: 'period',
      probe: 'lock_on_month',
      deepLink: '/periods',
      prerequisiteItemIds: ['no_drafts', 'statements_signed'],
      dueOffsetDays: 10,
    },
  ],
};
